server:
  port: 9081

spring:
  ai:
    openai:
      api-key: sk-jwymgqbadkolbcarzoknrqjihjpphtiauwpxcxggaadjcoxt
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2-7B-Instruct
      embedding:
        options:
          model: BAAI/bge-m3

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never

      client:
        observations:
          log-prompt: true

      observations:
        log-prompt: true

  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-abaejx7d.sql.tencentcdb.com:24524/aoaojiao-ai?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 32UkJQA_2!x2b.E
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        ai: DEBUG