server:
  port: 9081

spring:
  ai:
    openai:
      api-key: sk-jwymgqbadkolbcarzoknrqjihjpphtiauwpxcxggaadjcoxt
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen2-7B-Instruct
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never


  datasource:
    url: jdbc:mysql://localhost:3306/aoaojiao-ai?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

